[app]
	version = "v 0.1.0"
	title = "MapCloud Tiler"
[output]
	format ="mbtiles"
	conn="csnight:qnyh@123@tcp(127.0.0.1:3306)/streets-v8"
    directory="G:\\streets-v8"
[task]
	workers = 512
	savepipe = 4000
    redis = "127.0.0.1:6379"
[tm]
	name = "streets-v8"
	min = 15
	max = 15
	format = "pbf"
	schema = "xyz"
	url = "https://api.mapbox.com/v4/mapbox.country-boundaries-v1,mapbox.mapbox-streets-v8/{z}/{x}/{y}.vector.pbf?sku=101OxDPvepvQI&access_token=pk.eyJ1IjoiY3NuaWdodCIsImEiOiJjazRqanVydXMwYmtlM2VxODF1NDVtNWlsIn0.eGp2KkdstpJjiKdymjZ3sA"
    bound = '{"west":-180,"south":-85,"north":85,"east":180}'